name: BloodyCosmetics
authors: ["Vanic"]
description: BloodyCosmetics
api: [5.0.0]
version: 1.5.0+dev
main: Vanic\Bloody\Cosmetics\Main
load: POSTWORLD

permissions:
  bloodycosmetics.use:
    default: true
